# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

array <- function(input) {
    .Call(`_arrow_array`, input)
}

array_string <- function(array) {
    .Call(`_arrow_array_string`, array)
}

as_r_int <- function(array) {
    .Call(`_arrow_as_r_int`, array)
}

